### ISSUE TITLE
referencing step definitions from other assembly/project not working

### ISSUE THREAD

**Issue by dominik-niebuhr** [reqnroll/Reqnroll#985]
### Reqnroll Version

3.3.0

### Which test runner are you using?

xUnit 3

### Test Runner Version Number

3.1.5

### .NET Implementation

.NET 9.0

### Test Execution Method

Visual Studio Test Explorer

### Content of reqnroll.json configuration file
```json
{
  "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
  "formatters": {
    "html": {
      "outputFilePath": "TestResults/Reports/gabi_reqnroll_report.html"
    },
    "message": {
      "outputFilePath": "TestResults/Reports/gabi_cucumber_messages.ndjson"
    }
  },
  "bindingAssemblies": [
    {
      "assembly": "SBA.QualityAssurance.End2End.Shared"
    }
  ]
}
```

### Issue Description

After updating from 3.2.x to 3.3.0 the tests stopped working with something like this:

```
Given the user opens "GABI"
-> undefined: No matching step definition found for the step. Use the following code to create one:
        [Given("the user opens {string}")]
        public void GivenTheUserOpens(string gABI0)
        {
            throw new PendingStepException();
        }
```

this step definition is defined in the `SBA.QualityAssurance.End2End.Shared` assembly 

```csharp
[Binding]
public class ApplicationBinding(ApplicationSteps applicationSteps)
{
    [Given("the user opens {string}")]
    public async Task GivenTheUserOpensString(SBAComponent sbaComponent)
    {
        await applicationSteps.OpenApplication(sbaComponent);
    }
}
```

it even is recognized (still) by the reqnroll  rider plugin

### Steps to Reproduce

1) have project B with step definition
2) have project A with feature file using said step definition and have bindingAssembly setting setup
3) try to run test of project A
